version: '3'
services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: uTXukSvDgFXHTVzZ
    ports:
        - "5000:3306"
    volumes:
        - ./bd_init:/docker-entrypoint-initdb.d
  website:
        build: .
        ports:
            - "8080:8080"
        restart: on-failure
